#+TITLE:       关于Maven的一些笔记
#+AUTHOR:      Kelvin Hu
#+EMAIL:       ini.kelvin@gmail.com
#+DATE:        2012-10-12 Fri
#+URI:         /wiki/maven/
#+KEYWORDS:    java, maven
#+TAGS:        :Java:Maven:
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t
#+DESCRIPTION: records some notes during learning/practicing maven

Maven是一个用于java project management的工具，和Ant不同，Ant相当于make，你写一个task，它就执行一个task，你让它copy，它就copy；而Maven则是专注于更加high level的整个project的generation/management/compile/distribution等一系列操作。

* pom.xml文件中的一些node的作用：

  POM全称Project Object Model，在pom.xml中，以下结点是常用的，意义如下（摘自Maven Manual）：

  - =project= This is the top-level element in all Maven pom.xml files.

  - =modelVersion= This element indicates what version of the object model this POM is using. The version of the model itself changes very infrequently but it is mandatory in order to ensure stability of use if and when the Maven developers deem it necessary to change the model.

  - =groupId= This element indicates the unique identifier of the organization or group that created the project. The groupId is one of the key identifiers of a project and is typically based on the fully qualified domain name of your organization. For example org.apache.maven.plugins is the designated groupId for all Maven plug-ins.

  - =artifactId= This element indicates the unique base name of the primary artifact being generated by this project. The primary artifact for a project is typically a JAR file. Secondary artifacts like source bundles also use the artifactId as part of their final name. A typical artifact produced by Maven would have the form <artifactId>-<version>.<extension> (for example, myapp-1.0.jar).

  - =packaging= This element indicates the package type to be used by this artifact (e.g. JAR, WAR, EAR, etc.). This not only means if the artifact produced is JAR, WAR, or EAR but can also indicate a specific lifecycle to use as part of the build process. (The lifecycle is a topic we will deal with further on in the guide. For now, just keep in mind that the indicated packaging of a project can play a part in customizing the build lifecycle.)  The default value for the packaging element is JAR so you do not have to specify this for most projects.

  - =version= This element indicates the version of the artifact generated by the project. Maven goes a long way to help you with version management and you will often see the SNAPSHOT designator in a version, which indicates that a project is in a state of development. We will discuss the use of snapshots and how they work further on in this guide.

  - =name= This element indicates the display name used for the project. This is often used in Maven's generated documentation.

  - =url= This element indicates where the project's site can be found. This is often used in Maven's generated documentation.

  - =description= This element provides a basic description of your project. This is often used in Maven's generated documentation.

* Create a web project:

  : mvn archetype:generate -DarchetypeArtifactId=maven-archetype-webapp

  This will create a web project, and goes into interactive mode, to read groupId etc. from the standard input.
