#+TITLE:       简单的奠基仪式
#+AUTHOR:      Kelvin Hu
#+EMAIL:       ini.kelvin@gmail.com
#+DATE:        2011-03-26 Sat
#+URI:         /blog/%y/%m/%d/groundbreaking-ceremony-on-cnblogs/
#+KEYWORDS:    blog host selection
#+TAGS:        :Misc:
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: simple groundbreaking ceremony on cnblogs.com


*好吧，这是我第三个博客的第一篇文章。。在09年6月，我开始在人人网写东西；在同年12月，我开始在百度空间写东西；然后，在11年3月，我开始在博客园写东西。*

这一篇，就是我决定在博客园写东西时，写的第一篇，大概提了一下为什么离开人人网和百度空间。而现在离开博客园（其实也不算“离开”，我还是会在上面继续发东西的）的原因也很简单，我讨厌WYSIWYG类型的编辑器，例如word，例如博客园写新文章时的编辑器，这些编辑器初看确实很方便，但对于我这样的强迫症患者来说，我会不断调整布局，对齐之类的样式，直到它们完全一致。这直接导致我在样式上花的精力要 远大于在内容上花的精力，本末倒置；另外，我希望能保存一份自己写的东西的副本，万一哪天这些个博客服务商跪了，或者像google reader一样说关就关了，连哭都没地方哭的。

现在，我用org mode来写东西，作为一种纯文本的格式，我能更加关注于写的内容本身，而不是过多关心哪里该加粗，哪里该向前或者向后移两个毫米。而且，可以把这些org文件保存于自己的电脑和dropbox，不会再出现因服务商关闭而导致资料丢失的情况。然后，再选一个托管服务，利用[[https://github.com/kelvinh/org-page][org-page]]把它们发布出来共享给大家，比如现在就在[[http://pages.github.com][github pages]]。

下面是原文（未大改，稍作了一些格式上的调整）：

--------------------------------------------------------------------------------

我一直没有记东西的习惯，平时学什么东西，在看相关资料看懂之后，就“哦——”一下，“原来这个是这样做的”，或者“这个的原理是这样的啊”。在当时确实懂了，但一段时间不用之后，就又什么都忘了，又要去翻以前的Code，或者去百度Google，效率确实比较低。

后来我意识到这点，便开始记一些东西，把一些基础的东西记在纸介质上，一些小项目什么的就写在自己的“博客”里。只是，开始的“博客”选错了地方---校内网，后来，我发现校内根本不是记技术性东西的地方，那地方只适合上传一些不知道被PS过多少次的照片，还适合五分钟发一次脑残的状态，以及“十天保证过四六级”的分享。于是，我又把博客搬到百度空间，开始一段时间，看着每天都有十几个人访问，自我感觉还是很不错的。可是，中国的互联网就是这样，某一种应用一旦红起来，所有的公司就开始拼命模仿。好好的百度空间，非得模仿校内这种SNS网站，给整个个人中心出来，各种脑残应用也出来了，这我还忍受了，但是后来，上面也开始有人上传精美的PS作品，于是，我再也忍不了了，遂废弃了在百度空间的博客。

平时遇到问题，也在博客园里逛，寻找问题的答案，自认为这确实是个不错的地方。但鉴于自己所知甚少，而这里又高手如云，所以一直未敢在这里开通博客，怕班门弄斧。但现在，马上就要毕业，工作已经找到，还有几个月就要上班了，干这一行，总要记东西的，于是决定把博客搬到这里来，毕竟这里要比百度空间什么专业多了。之前写在百度空间里的东西，因为转入太麻烦，所以就不转了，在这里重新开始吧。

另外，因为我昨天22岁生日，所以本来打算昨天写这一篇的，但昨天比较忙，后来居然忘掉了，所以就今天补上。希望这是一个好的开端，也希望我能坚持下去。

:                                 ---  ini_always  11.03.26  记于hust
