#+TITLE:       又是一年毕业季
#+AUTHOR:      Kelvin Hu
#+EMAIL:       ini.kelvin@gmail.com
#+DATE:        2012-06-30 Sat
#+URI:         /blog/%y/%m/%d/graduated-after-one-year/
#+KEYWORDS:    life
#+TAGS:        :Life:
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: happy memory in university


*这是我在博客园的博客中的文章。毕业一年时写的文章。*

/在整理这篇文章的时候，偶然发现，现在的时间是13年6月30号，而写这篇文章的时间是12年6月30号，刚好又过了一年。虽然两年已经过去了，但大学的那些美好的记忆却依旧清晰地刻在我脑海中，每每想起其中的一两件事时，我的嘴边，都会浮出微笑。谢谢我的大学，谢谢我在大学时遇到的诸位，以及和你们在一起的四年美好时光。/

下面是原文（未大改，稍作了一些格式上的调整）：

--------------------------------------------------------------------------------

前几日，在校内上，看到一些关于08级毕业的照片，顿时往日的记忆就被勾起。

又到六月，一个属于毕业和伤感的季节。

去年六月二十五号，踏上离开HUST的火车。本打算悄悄地走，但被一帮基友发现，于是一起送我，我坚持着一路说笑，还和同班的一个妹子来了一个拥抱，一副很轻松的样子。可是，在坐上出租车，关上车门、回头说再见的那一刹那，眼泪却瞬间流下。HUST四年，我记不清上过什么课，学到什么东西，我已经记不清很多东西，可是，我却记得，我有一帮好基友。

一年过去，当年的基友们也在五湖四海，读研的读研，出国的出国，工作的工作，再也没有往日“一呼百应”的日子：

#+BEGIN_QUOTE
“打球！”  “走！”

“dota！”  “搞起！”

“吃饭！”  “帮带！”

“上课！”  “帮答到！”
#+END_QUOTE

而我也来到南京这样一个没有亲人和基友的地方，开始一个人上班下班，一个人过周末的苦逼日子。其实，我多想回到过去，再去宿舍旁的食堂吃顿饭，再去代表班级打一次篮球，再去为院足球队吼两声“加油”，再去VS上开一次五人黑，再去听一次根叔的毕业演讲，再去体验一次HUST独有的毕业游行方式。。。只是，时间向前，我们已无法回去。

虽然时光已不再，但是，还是感谢那些陪伴我四年的基友，谢谢你们，在生命最好的年华里，没有妹子，没关系，我有一帮好基友。

毕业一周年，写些废话，以祭那些我们一起SB的岁月，以及我那没有妹子的青春。

: ---  Kelvin  6/30/2012  记于南京
