#+TITLE:       愿你们的国降临
#+AUTHOR:      Kelvin Hu
#+EMAIL:       ini.kelvin@gmail.com
#+DATE:        2013-12-07 Sat
#+URI:         /blog/%y/%m/%d/may-you-rest-in-peace/
#+KEYWORDS:    亲人, 外公, 三姨, 生命, 死亡
#+TAGS:        :Life:
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: 谨以此文，献给我那已远在天国的亲爱的外公，三姨


周末给家里打电话，才知道，外公走了，永远地离开了我们，而我那一刻却远在千里之外。而一个月之前，三姨也刚刚离去。短短一个月，接连离去两位亲人，想想之前的一些温馨过往，悲伤不已，遂提拙笔，写些文字，献给我那已远在天国的亲爱的外公、三姨。

* 三姨

  去年的时候，有一次和家里打电话，才突然知道，三姨去医院检查时，发现得了妇科坏病，而且已经到了晚期。我当时非常惊愕：三姨才五十多岁，还相当年轻，不知为何病魔就找上她了呢？之后，虽然有去医院化疗，但因为已经晚期，回天乏术，最终在一个月前，不幸离世。

  我清楚地记得那天早上，父亲给我打电话时，我还在床上。他告诉我这个消息时，三姨已经到了头七。这个消息又让我惊愕不已：怎么说去就去了。。

  那几天，我的脑海里一直都是三姨熟悉的身影。想起小时候，有一次暑假去她家玩儿，我到的时候她们正好在吃午饭，我就跟着一起吃。三姨为了招待我，特地去家边的商店买了几瓶啤酒。要知道，当时可是家里来了重要的客人才会去买啤酒的，而我当时不过是个十岁左右的小屁孩。。

  稍感欣慰的是，我的表弟，也就是姨老表，在三姨生病的时候，一直在家照顾她，做饭洗衣，忙里忙外。能养出这样孝顺的儿子，我想三姨应该也算满足了吧。三姨操劳了一辈子，在男人们都外出打工挣钱的时候，她一个人在家，猪狗鸡鸭，家里田间，全由她操心。现在，她终于可以歇一歇了。

* 外公

  年初的时候，又是跟家里打电话时才知道，外公的咽喉检查出了问题。后来，只知道外公吃饭越来越少，在我十一放假回去看望他老人家的时候，他的头发已经全部花白，几乎吃不进东西。不过当时意识还比较清醒，还能够认出来我。只是没想到在我走后，他老人家的情况迅速恶化，发展到只能靠打能量来维持。于是，一周前，家里打来电话，说外公快走了，但随即父亲又突然打电话来，说外公又好了，还能和他谈天说地，聊一些过去的往事。我很高兴，还以为外公又撑过了一关呢。

  只是我没想到，这只是回光返照。第二天，外公就走了。

  小的时候，外公经常去我家，帮忙做家具。那是我最高兴的时候，因为一到晚上，我就会缠着他老人家讲故事，他也很乐意，每次的故事都会逗得我哈哈大笑，然后我第二天去学校讲给同学听，又逗得他们哈哈大笑。而外公在我家忙完，要回家的时候，是我最不舍的时候，我总是抱着他的脚，拽着他的衣服不让他走，他总是骗我说过两天就来。我不相信，可是没有办法，我拗不过他，然后就只能眼睁睁看着他走远，伤心好一阵子。

  后来，我去外地上学了，和外公见面的机会就少了；再后来，我家搬到离外公家更远的地方，见面的机会就更少了。

  现在，外公走了，小时候听他讲的那些故事，现在在我脑海中只剩下一些断断续续的残片，只是这些故事再也没有办法串起来了。

--------------------------------------------------------------------------------

过年回家的时候，我特意回老家了一趟，去看望在离世的时候我不在身边的外公和三姨，给他们烧些纸钱。直到那时候，我都不敢相信，音容笑貌仍在我脑海中回荡的亲人，竟然就这么去了！只剩一座孤零零的坟头，告诉后人，有一位曾经养育过你们的先人，安眠于此。

想起前一阵子，一个朋友的外公过世。她外公是当地的名医，于是当地的新闻媒体各种报道，社会各方也前去吊唁。而我的外公和三姨，普普通通，没有新闻媒体的报道，除了亲戚邻居之外，也没有别人前去吊唁。

是的，名人故去，会有媒体报道，会有大众吊唁，甚至还会有别人为他们写传。而我的外公和三姨，平平常常，最终，只化为一抔黄土，继续润泽他们一生劳作其上的土地。对大众而言，他们是渺小的；但对我们而言，他们却是伟大的，他们养儿育女，一生操劳，他们支撑起整个家族，让这个家族在这块土地上一直繁衍下去。

亲爱的外公，三姨，你们生前一生操劳，现在，你们可以好好歇歇了。愿你们在天国安以宁静，你们在我们的心中永生。


———— 晚辈 涛 敬上
