#+TITLE:       岁月如歌——甘十九妹
#+AUTHOR:      Kelvin Hu
#+EMAIL:       ini.kelvin@gmail.com
#+DATE:        2016-01-24 Sun
#+URI:         /blog/%y/%m/%d/time-is-like-a-song/
#+KEYWORDS:    Life
#+TAGS:        Life
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil ::t |:t ^:nil -:nil f:t *:t <:t
#+DESCRIPTION: 回忆往事，岁月如歌


“如果来生还是今世的重复，纵然多情要比无情苦；如果来生还是今世的重复，你是否还是这样不在乎。”几天前在哼歌的时候，不知为何，突然就哼到了这首《甘十九妹》的片尾曲。然后就想起这部在我只有几岁的时候播出的电视剧来。顺手在网上搜了一下，发现竟然有视频，于是便花了几个晚上重温了一遍。

在此之前，这部剧我已经看过两遍。第一遍是在我只有几岁的时候（查了一下，《甘十九妹》第一次播出的时候是1996年，那时候我7岁），当时家里并没有电视，不过外婆家有一台大概十几寸的电视机，还是黑白的。那是在暑假（或者是寒假？）去外婆家玩的时候，刚好这部剧在播出。但年龄毕竟太小，说是看电视，也不过是跟着大人一起凑凑热闹，然后削一些竹棍当剑，模仿电视里面和小伙伴“咯儿咯儿”地“比武”罢了。剧情全都忘了，仅有的一点印象就是最后的决斗，尹剑平杀了甘十九妹后自杀，然后抱在一起死去。但那时候7岁的我自然无法理解：这两个人是怎么回事？为什么互相杀对方然后又抱在一起？

第二次看的时候，应该是在初中。那时候家里已经买了彩色电视机，但具体是哪一年已无法记起，只依稀记得电视放在高高的柜子上，晚上爸妈都睡觉后，我一个人守在电视前，等待着“书上侠客万般神通”的歌声响起。这一次，除了最后的决斗场面外，另外一个镜头也给我留下了无法抹除的记忆：在一个火堆前，甘十九妹头伏在腿上轻轻啜泣，尹剑平走过去，怜惜地轻抚她的长发。对于这个镜头的前因后果，倒是毫无记忆。我至今仍深深记得最后两人抱在一起死去时，我一个人在电视前，泪如泉涌，久久不止。虽然自身尚未经历过爱情，甚至无法清楚意识到为何而哭，但毕竟已到了懵懂的年龄。为何别的剧情全无记忆，而唯独记得这两个镜头？现在想来，倒也很好解释：一个是爱情之美，一个是爱情之悲，确实都是能给人留下深刻印象之事。

这次重温，自是感慨万千，以至于最后看完时，时间虽然已是凌晨六点，但我却久久不能睡去。不过这感慨已与过去不同，除了感慨两人凄美纯粹的爱情外，还有时间：似乎眨眼之间，时间已过去二十年。

“是非恩怨终究都会成空，人生在世图个快意恩仇，有些事你不必太在乎，许多条路就在你前头。”1996年，我哼着这首歌时，才7岁；2016年，我再次哼着这首歌时，已二十有七。二十年岁月已逝，其间多少记忆，都如昨日。二十年前，“甘十九妹”只有23岁，如仙女下凡，不食人间烟火，冰清玉洁，最是美丽动人；二十年后，伊已年过不惑，已是两个小孩的母亲。二十年前，我只是一个贪玩小孩，每天只知“舞刀弄棒”；二十年后，我已年近而立，我的脸上，尽是沧桑。
