#+TITLE:       Org Mode Manual Learning Notes
#+AUTHOR:      Kelvin Hu
#+EMAIL:       ini.kelvin@gmail.com
#+DATE:        2012-07-21 Sat
#+KEYWORDS:    org mode
#+CATEGORY:    notes
#+TAGS:        :Org Mode:
#+LANGUAGE:    en
#+OPTIONS:     H:3 num:nil toc:nil \n:nil @:t ::t |:t ^:nil -:t f:t *:t <:t
#+DESCRIPTION: learning notes of org mode manual

Learning notes recorded during reading org mode manual, simple and incomplete,
because they are all about basic syntax.

* headers

Headers are lines started with star * (be careful that there should not be any indent before the star, otherwise it will be an item of a list, not a header).

The first level header is with one star *, and the second with two stars, and so on.

* lists

** unsorted lists

Unsorted list items start with -, + or *, but the star is NOT recommanded because it is not easy to distinguish it from headers.
- so, this is an unsorted list item using -
- this one using +

** sorted lists

Sorted list items start with 1. or 1), if =org-alphabetical-lists= is configured, a. a) A. A) can also be used.
1) sorted list item using a right parenthesis )
2. using a period .

** description lists

Description list items are unsorted list items, which contain separator :: to distinguish /description term/ from /description/.

+ description example :: this is a description for the "description example"

* foot notes

Footnotes are made in square brackets, start with "fn:", and then follow a name, e.g. "1" or "kelvin".

my blog on cnblogs[fn:1]

my blog on github[fn:kelvin]

* tables

create a table is very easy, like what I am doing below:

|-----------+---------+-------------------|
| name      | age     | job               |
|-----------+---------+-------------------|
| Kelvin Hu | 23      | Software Engineer |
|-----------+---------+-------------------|
| Someone   | Unknown | Unknown           |
|-----------+---------+-------------------|



several useful key bindings:

1) =C-c -=   :: mapping command is /org-table-insert-hline/, will insert a separate line below
2) =C-c RET= :: mapping command is /org-table-hline-and-move/, insert a separate line and move to next row
3) =C-c |=   :: mapping command is /org-table-create-or-convert-from-region/, create or convert table

* links

Links exist between two square brackets, like below:

[[http://kelvinh.github.com][kelvin's github blog]] or [[http://kelvinh.github.com]]


useful key bindings:

- =C-c C-o= :: /org-open-at-point/, open the link in browser

for more information about links, please visit offical org doc: [[http://orgmode.org/org.html#Link-abbreviations][click here]]

* markup rules

** title

The line below will be considered as the title of this document:
#+begin_src org
  #+title: the line will be used as the title of current document

  note that the case is not sensitive, so #+title: will have the same effect as #+TITLE:
  and also do not forget the colon ":"
#+end_src

** several other useful syntax

#+begin_src org
  #+BEGIN_VERSE and #+END_VERSE: the contents between the two tags will be outputed originaly, with no format

  '#+BEGIN_QUOTE' and '#+END_QUOTE': the contents between the two tags are treated as quoting
  (why I add a quote ' here? you may try it then you will know why I add it here ^_^)

  #+BEGIN_CENTER and #+END_CENTER: the two tags will center the contents between them
#+end_src

** emphasis and monospace

As the offical doc says, you can make word *bold*, /italic/ and _underlined_, and also +strike through+.\\
also there are other two syntax: =code= and ~verbatim~, I do not quite know what they are used for.

** horizontal rules

a line with at least 5 dashes and only contains dashes will be converted into a horizontal line, like below:
--------------------------------------------------------------------------------------------------------------------

** comments

several rules:
#+begin_src org
1) lines start with #
2) indented lines start with #+
3) contents between #+BEGIN_COMMENT and #+END_COMMENT
4) entire subtree starts with keyword COMMENT
#+end_src

=C-c ;= can toggle the COMMENT keyword at the beginning of an entry

note: all comments will *NOT* be exported

** useful syntax again

#+begin_src org
  '#+begin_example'
     example here...
  '#+end_example'

  '#+begin_src <syntax> [-n -r]'
     some code here...
  '#+end_src'
#+end_src
the <syntax> stands for the type, e.g. emacs-lisp

e.g. as below:

#+begin_src emacs-lisp -n
(defun hello-world()
  (print "hello world"))
#+end_src

#+begin_src java
public class Test {
    public static void main(String[] args) {
        System.out.println("hello world");
    }
}
#+end_src

** include files

for example: *#+include: "~/.emacs.d/init.el" src emacs-lisp* will insert the contents of ~/.emacs.d/init.el at current position, as below:\\
(the second parameter is the tag type, "src" stands for "#+begin\_src/#+end\_src" pair, so do "quote" and "example")

#+include: "~/.emacs.d/init.el" src emacs-lisp



-------------------------------------------

[fn:kelvin] http://kelvinh.github.com

[fn:1] http://www.cnblogs.com/ini_always
